title: SecureBookmark
description: Security critical web apps with Data URI and subresource integrity. By Robin Linus and Egor Homakov
theme: minima
social_links:
  github: coins
  twitter: coins_research
